### ISSUE TITLE
Code Review for IngredientAddActivity

### ISSUE THREAD

**Issue by CaferTayyar** [bounswe/bounswe2015group2#175]
Can you review my piece of code in here https://github.com/bounswe/bounswe2015group2/blob/android/aciktim-andriod/app/src/main/java/edu/boun/cmpe451/group2/android/ingredient/IngredientAddActivity.java? If you find any bug or unclarity in code, please comment it to the code.

**Comment by ugur2889** [comment]
OK .I will review your code.

**Comment by ugur2889** [comment]
In your commit, Your code is preety clear, and also is  understandable for everyone.
Functions and variable names are also understandable.
As far as I can see, there are no bugs in this commit.
There are no comments in your commit  ,also  code documentations. I think You will add them as soon as.
I believe that  I can modify this commit easily because the code is very clear and I also take part in the  android project.
The Code doesn't include tests but after that you can add unit tests..
I didn^t  run code analysis tools because you use android studio you can use Android Lint automatically.
Generally,Your commit is easily modifiable   and understandable for everyone.

**Comment by CaferTayyar** [comment]
I added some comments for clarity of the code
