### ISSUE TITLE
Code Review : Implements Daily Consumption Summary

### ISSUE THREAD

**Issue by oeken** [bounswe/bounswe2015group2#178]
Please review it, and feedback me.

**Comment by bmertcotuk** [comment]
Sure. I will review your code and give a detailed feedback.

**Comment by bmertcotuk** [comment]
I reviewed your code. You can find the detailed feedback here:
https://docs.google.com/document/d/145ByswbaC-Cbw0sChX46CZfUNydAaRcAJZCN77IXGOA/edit?usp=sharing

**Comment by bmertcotuk** [comment]
**Code Review**

**Code Clarity**
Your code seems clear and readable.

**Bugs & Missing Features**
I ran the code several times and encountered no bugs.

**Coding Convention**
In this commit you have made some changes in variable names. For instance, you modified the variable names of ‘date’ and ‘queried_date’ and replaced them in few lines. This made code more reliable. I also saw some modifications in indentations and white spaces which increases the readability. The code was self-explanatory and did not require any comments in this commit.

**Code Documentation**
Maybe putting a few lines for Javadoc be helpful.

**Unit Testing**
I was not able to find any unit tests. You can test the code by trying edge cases for day, month, and year (negative numbers, zero ...etc.).

**Ease of Modification**
The code seems easy to modify since it is readable and written regarding the coding conventions.

**Opinion about Style**
Changing the method name ‘userdailyconsumption’ to ‘userDailyConsumption’ maybe better to meet the Java coding standards.

**IntelliJ Code Analysis**
I performed a code analysis for your commit. Only warning I got was ‘queriedCal’ variable may be null and throw null pointer exception. The IDE suggest to check whether it is null or not before using it. However, you have already handled this case with a try/catch block.
