### ISSUE TITLE
Code Review : Updates the advanced search content bar to give it a better look

### ISSUE THREAD

**Issue by bmertcotuk** [bounswe/bounswe2015group2#180]
Please review it, and give a feedback for the commit below:

https://github.com/bounswe/bounswe2015group2/commit/4414c043561c9f4553aa7e3e82c70d5d4e4f9133

NOTE: The name of the commit is a bit misleading. It actually does a major work for advanced search functionality.

**Comment by erensogut** [comment]
I start to preview 4414c04.It would be done in an hour.

**Comment by erensogut** [comment]
In the first view the commit, it looks considerable clear, and also is understandable for everyone.
Functions and variable names are chosen sensefully and so they are understandable.The comments are not very much but work spot on.Maybe add some comment and take care to be in english ,help to improve the code understandability.It is easy to modify this code because it is clear and generally has comment.Also function and other structure are used effectively and this improve the quaility of the code.
Some function does not have javadoc info but I believe it takes nearly any time for you.
After all this first impressions ,I run the code analysis tool that IntelliJ Code Analyzer and learn how to utilize it from https://www.jetbrains.com/idea/help/code-analysis.html.
It gives a javadoc error which is
Name :public method ArrayList<Recipe> searchRecipes(String name, List<String> ingredients)  
Location : class RecipeDao (edu.boun.cmpe451.group2.dao)    
Problem synopsis      '@return' tag description is missing (at line 66)
And another error which can be probable bug
Name : public method void updateRecipe(Recipe recipe) 
Location  : class RecipeDao (edu.boun.cmpe451.group2.dao)   
Problem synopsis : Variable 'sql2' at line 441 is never used
The analyzer also shows some spelling mistake but when I examine them ,they all are not problematic.So there is no problem to report.

**Comment by bmertcotuk** [comment]
Thank you for your feedback. I modified the code according to your feedback given in the code review. I also added the Javadoc comments. Now I am working on tests.

**Comment by bmertcotuk** [comment]
I have tested the code again and again and encountered no errors. I found a tutorial on testing the controller files in Spring MVC from the link below:
http://www.javacodegeeks.com/2012/10/spring-mvc-controller-junit-testing.html

I wrote a test class and created a test directory for that. However, I was not able to commit and push it here. I would like to get some help. 

The test class I wroted for my method is below:

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes={ JpaTestConfig.class, TestConfig.class })
public class RecipeControllerTest {

    private MockMvc mockMvc;

    @Before
    public void setup() {

        mockMvc = MockMvcBuilders
                .annotationConfigSetup(JpaTestConfig.class, TestConfig.class)
                .build();

    }

    @Test
    public class testViewrecipes throws Exception {

        mockMvc.perform(get("/recipes"))
                .andExpect(status().isOk())
                .andExpect(forwardedUrl("user-views/recipes"))
                .andExpect(model().attributeExists("bad_attempt"))
                .andExpect(model().attributeExists("isInst"))
                .andExpect(model().attributeExists("full_name"))
                .andExpect(model().attributeExists("recipeResults"))
                .andExpect(model().attributeExists("content_bar_selection"));
    }
}
