### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by denizbaloglu** [bounswe/bounswe2015group2#181]
Could you please review following functions?

- updateRecipe method in model/RecipeModel
- getRecommendations in dao/RecipeDao

**Comment by mcenkbatman** [comment]
I have another code review assignment so I assigned onur

**Comment by denizbaloglu** [comment]
All right!

**Comment by onesvat** [comment]
- **Code clarity:** Your code is very clear. There is no unnecessary lines.
- **Bugs:** I did not find any bugs
- **Missing Features:**  There is no missing fetaurees
- **Variable names:** Some of the variable names in loops are unmeaningful, like "for(Map<String,Object> map: recipes)", maybe rather than map, you can use recipe.
- **Indentation:** Indentation is perfect.
- **Comments:** There is no comments at all. In the updateRecipe, everything is fine but, in the getRecommendations there are some numbers which I don't what they are. Little comments on this method would be nice
- **Incomplete Code Documentation:** Your methods needs javadoc style documentations, (input, output parameters)
- **Coverage with unit tests:** There is no tests yet, but most of the edge cases throws exceptions on updateRecipe method. In the getRecommendation method, you can test recommendations by giving some specific variables, Eg assert that user has eaten carbohydrates and fats, expect that the recommendation method will give protein based recipes.
- **IntelliJ Code Analyser:** No errors

In overall, it is good implementation especially getRecommendations has good algorithm.
