### ISSUE TITLE
Code Review:view Recipe

### ISSUE THREAD

**Issue by erensogut** [bounswe/bounswe2015group2#183]
Please review it, and give a feedback for the commit below:
a582fd2

**Comment by bmertcotuk** [comment]
Code clarity: considerable clear, and also is understandable for everyone.
Coding convention:Functions and variable names are chosen sensefully and so they are understandable.The comments should be improved.Maybe add some comment,help to improve the code understandability.It is easy to modify this code because it is clear .Also function and other structure are used effectively and this improve the quaility of the code. Javadoc must be coded.
After all this first impressions ,I run the code analysis tool that IntelliJ Code Analyzer .It gives some unimportant error and make cautions such as:
Name: public method String recipeedit(Long recipe_id, String image_url, String recipe_name, String description, String session_id, ModelMap model)    
Location: class RecipeController (edu.boun.cmpe451.group2.controller)   
Problem synopsis      Variable 'userId' at line 344 is never used 
And also shows some spelling mistake which are actually not mistake.
